### ISSUE TITLE
Again '/node_modules/eventemitter3/index.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by MarcelFinkbeiner** [sindresorhus/p-queue#185] opened 2023-05-12 12:52 UTC
Hello,

I get the following error in one of my projects:
the requested module '/node_modules/eventemitter3/index.js' does not provide an export named 'default' (at index.js:13:8)

**The index.js file (in the error) refs to /node_modules/p-queue/dist/index.js**

Package version: 
```json
"p-queue": "^7.3.4",
"typescript": "^5.0.2",
```

TS Config:
```json
{
  "compilerOptions": {
    "module": "ES6",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "allowJs": true,
    "target": "ES6",
    "useDefineForClassFields": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "jsx": "preserve",
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["ES6", "DOM"],
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

Please let me know if you need additional inforamtion!

Best regards
Marcel

**Comment by sindresorhus** [comment] 2023-05-12 12:59
Duplicate of #185

**Closed by sindresorhus** 2023-05-12 12:59 UTC
