### ISSUE TITLE
Error in Typescript

### ISSUE THREAD

**Issue by rupamking1** [sindresorhus/p-queue#152] opened 2021-07-15 19:26 UTC
[INFO] 00:51:40 Restarting: C:\test\Test.ts has been modified
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\_test\node_modules\p-queue\dist\index.js
require() of ES modules is not supported.
require() of C:\test\node_modules\p-queue\dist\index.js from C:\_test\Test.ts is 
an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\test\node_modules\p-queue\package.json.
    at new NodeError (node:internal/errors:363:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1126:13)
    at Object.nodeDevHook [as .js] (C:\Users\iotu\AppData\Roaming\npm\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\test\Test.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module._compile (C:\Users\iotu\AppData\Roaming\npm\node_modules\ts-node-dev\node_modules\source-map-support\source-map-support.js:547:25)
[ERROR] 00:51:42 Error: Must use import to load ES Module: C:\test\node_modules\p-queue\dist\index.js
require() of ES modules is not supported.
require() of C:\test\node_modules\p-queue\dist\index.js from C:\test\Test.ts is 
an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\test\node_modules\p-queue\package.json.

**Comment by itstyonirwansyah** [comment] 2021-07-18 10:53
I also got the same error as well. 

>  ```code: 'ERR_REQUIRE_ESM'```

**Comment by ErunamoJAZZ** [comment] 2021-07-20 23:50
Same here. Using TypeScript 4.3.5.

**Comment by paularah** [comment] 2021-07-21 02:36
> Same here. Using TypeScript 4.3.5.
> 
> ~Edit: I figured the target in my tsconfig.json was `es6`, I updated this to `ES2020` and I dont have this error now :)~ Forget it

I don't think this is a lasting solution, most people are probably using Node 12 - 14 in prod and wouldn't  want to set their typescript target to ES2020

**Comment by ErunamoJAZZ** [comment] 2021-07-21 02:39
At end, nothing worked. A downdrade to `"p-queue": "^6.6.2",` was the unique solution for now.
This change was introduced in the 7.x version https://github.com/sindresorhus/p-queue/releases/tag/v7.0.0
Instructions to migrate a project to use ESM were provided but didn't work.

This package was the unique one that give me problems, but to be honest, Im not sure how to fix it directly to send a PR or something :(

**Comment by lockHrt** [comment] 2021-08-19 13:53
I followed all instructions to convert my typescript project to pure ESM as per [this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). Typescript is broken now. I don't see any way to get 7.x version to work with typescript.

**Comment by Richienb** [comment] 2022-02-01 05:27
Duplicate of https://github.com/sindresorhus/p-queue/issues/144

**Closed by Richienb** 2022-02-01 05:27 UTC

**Comment by binkyo1116** [comment] 2022-11-28 14:01
Yeah, I also think downgrading into ^6.6.2 is only solution now.

**Comment by Apollon77** [comment] 2022-11-28 14:28
In fact there is another option ... migrating to https://github.com/esm2cjs/p-queue which is an "automatic rebuild of the main package but as dual package

**Comment by motiejunas** [comment] 2022-12-18 00:19
Downgrading into 6.6.2 did the trick.

**Comment by Apollon77** [comment] 2022-12-18 11:13
@motiejunas Yes with the effect of missing security updates

**Comment by eladcandroid** [comment] 2022-12-18 13:25
Any better solution?

**Comment by Apollon77** [comment] 2022-12-18 13:54
Yes ... have a look 3 posts higher ... or use this quick-link to help scrolling :-) https://github.com/sindresorhus/p-queue/issues/152#issuecomment-1329208852

**Comment by des-psl** [comment] 2024-04-01 23:42
I am still getting the same error with Jest for p-queue 8.0.1. Must I use this library: https://github.com/esm2cjs/p-queue? I would rather not

**Comment by SwapnilSoni1999** [comment] 2024-11-03 12:09
> I am still getting the same error with Jest for p-queue 8.0.1. Must I use this library: https://github.com/esm2cjs/p-queue? I would rather not

this repo looks older than this original repo 
Last updated 2years ago (esm2cjs)
this project updated almost a year ago
