### ISSUE TITLE
Property '_doesIntervalAllowAnother' implicitly has type 'any'

### ISSUE THREAD

**Issue by ChristianBoehlke** [sindresorhus/p-queue#89] opened 2019-11-11 12:30 UTC
Hello,

Thank you for the great work with this library! We tried upgrading from version 6.2.0 to 6.2.1 and are getting the following TypeScript compiler errors:

```
node_modules/p-queue/dist/index.d.ts:28:17 - error TS7033: Property '_doesIntervalAllowAnother' implicitly has type 'any', because its get accessor lacks a return type annotation.

28     private get _doesIntervalAllowAnother();
                   ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/p-queue/dist/index.d.ts:29:17 - error TS7033: Property '_doesConcurrentAllowAnother' implicitly has type 'any', because its get accessor lacks a return type annotation.

29     private get _doesConcurrentAllowAnother();
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We are using TypeScript 3.6.4 and have `noImplicitAny: true` set.

The [type definitions for version 6.2.0](https://unpkg.com/browse/p-queue@6.2.0/dist/index.d.ts) declared them as private variables:
```typescript
private readonly _doesIntervalAllowAnother;
private readonly _doesConcurrentAllowAnother;
```

The [type definitions for version 6.2.1](https://unpkg.com/browse/p-queue@6.2.1/dist/index.d.ts) now declare them as private getters:
```typescript
private get _doesIntervalAllowAnother();
private get _doesConcurrentAllowAnother();
```

Maybe that's why TypeScript treats them differently?

Thank you for you help!

**Comment by sindresorhus** [comment] 2019-11-11 13:14
Looks like it was fixed in TS 3.7.2, but I think you have to upgrade to that version: https://github.com/microsoft/TypeScript/commit/e48cd3a1011ba0b61edee0cc19201cff8ff6f6e6

**Comment by georgyfarniev** [comment] 2019-11-12 10:15
@sindresorhus I cannot upgrade to latest typescript, since it will break many things in my monorepo (nuxt, vue, etc have some issues). How about adding explicit type annotations please?

**Comment by sindresorhus** [comment] 2019-11-12 10:22
It does have a type annotation: https://github.com/sindresorhus/p-queue/blob/c2e768f540dd22380bdf84c8cbd5a794ccac5e02/source/index.ts#L91 The problem is explained in the linked commit. Not much I can do to work around it. I suggest you just pin the `p-queue` version to `6.2.0` until you can upgrade TypeScript.

**Comment by sindresorhus** [comment] 2019-11-15 06:38
More discussion about it here: https://github.com/microsoft/TypeScript/issues/35016

**Closed** 2021-01-08 16:26 UTC
