### ISSUE TITLE
Fails to minify the code when used with create-react-app

### ISSUE THREAD

**Issue by ghoshnirmalya** [sindresorhus/p-queue#30] opened 2018-03-28 10:55 UTC
The code fails to minify because of this package. The `yarn build` fails with the following output:

```
...
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/p-queue/index.js:6 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

**Comment by sindresorhus** [comment] 2018-03-28 11:11
Duplicate of #7

**Closed by sindresorhus** 2018-03-28 11:11 UTC
