### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by randal923** [sindresorhus/p-queue#151] opened 2021-06-12 06:27 UTC
I am getting this error but I am using import.

Node version 14.15.4

Code:

```
import axios from 'axios'
import fs from 'fs'
import PQueue from 'p-queue'

async function getApplicants (): Promise<void> {
  const queue = new PQueue({ concurrency: 4 })

  for (let i = Number(page) + 1; i < Infinity; i++) {
   "..."
    const respose = await queue.add(async () => await axios.get('url'))
   "..."
  }

  await queue.onIdle()
 
 "do stuff..."
}

export default getApplicants
```

package.json: 
```
{
  "name": "api",
  "version": "0.0.1",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "nodemon src/server.ts",
    "debug": "nodemon -L --watch ./dist --inspect=0.0.0.0:9222 --nolazy ./dist/main/server.js",
    "start": "NODE_ENV=production pm2 start dist/server.js --name='api'",
    "build": "rimraf dist && tsc -p tsconfig-build.json",
    "test": "jest --passWithNoTests --silent --noStackTrace --runInBand",
    "test:verbose": "jest --passWithNoTests --runInBand",
    "test:unit": "yarn test --watch -c jest-unit-config.js",
    "test:integration": "yarn test --watch -c jest-integration-config.js",
    "test:staged": "yarn test --findRelatedTests",
    "test:ci": "yarn test --coverage"
  },
  "devDependencies": {
  },
  "dependencies": {

  },
  "resolutions": {
    "@types/express/@types/express-serve-static-core": "4.17.20"
  },
  "_moduleAliases": {
    "@": "src"
  }
}
```

tsconfig:

```
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "commonjs",
    "target": "es2019",
    "esModuleInterop": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "baseUrl": "./src",
    "paths": {
      "@/*": [
        "*"
      ]
    }
  },
  "include": [
    "src"
  ],
  "exclude": []
}
```

![20210612062829605](https://user-images.githubusercontent.com/37159957/121767393-49ade780-cb2e-11eb-9574-508971474b14.png)

**Comment by sindresorhus** [comment] 2021-06-12 07:14
Duplicate of #151

**Closed by sindresorhus** 2021-06-12 07:14 UTC
